"""SQLAlchemy Base and model registrations."""
from app.core.database import Base
from app.db.models import (
    AIFileAnalysis,
    AdminAction,
    AdminUser,
    ConnectedAccount,
    EmailVerification,
    LoginLog,
    OTPAttempt,
    PasswordResetToken,
    PrivacyScan,
    SecurityScore,
    Session,
    TwoFactorConfig,
    TwoFactorRecoveryCode,
    User,
    VaultAuditLog,
    VaultFile,
)

__all__ = [
    "Base",
    "User",
    "Session",
    "OTPAttempt",
    "EmailVerification",
    "LoginLog",
    "ConnectedAccount",
    "PasswordResetToken",
    "VaultFile",
    "VaultAuditLog",
    "TwoFactorConfig",
    "TwoFactorRecoveryCode",
    "AdminUser",
    "AdminAction",
    "AIFileAnalysis",
    "PrivacyScan",
    "SecurityScore",
]
